### ISSUE TITLE
failed to execute query  - Hrana STREAM_EXPIRED

### ISSUE THREAD

**Issue by juliuslipp** [tursodatabase/go-libsql#13]
Hey Guys,

I am getting the following error after ~10s of the connection to the DB being alive:
```
failed to execute query 
...
error code = 1: Error executing statement: Hrana: `api error: `{\"message\":\"The stream has expired due to inactivity\",\"code\":\"STREAM_EXPIRED\"}
```

Makes this client more or less unusable (don't want to create a new connection on each request...). Would also be nice to see relative paths working with the client for the embedded replicas. 

Thanks! 

Repo to reproduce:
https://github.com/juliuslipp/libsql-weirdness

**Comment by haaawk** [comment]
Regarding relative paths, just do:
```
config := NewClientConfig("file:data/sqlite.db", nil)
```
instead of
```
config := NewClientConfig("file://./data/sqlite.db", nil)
```

**Comment by haaawk** [comment]
Regarding:
```
// Works - sometimes randomly (happend 3-4 Times with 100x restarts) leaves a sqlite.db which is empty after restarting. This breaks the whole app and there's no way of recovering except for deleting the file.
	config = NewClientConfig(dbUrlRemote, &dbAuthToken)
	dbRemoteEmbed, err := NewEmbeddedClient(config)
	if err != nil {
		fmt.Printf("Error Remote Embedded: %s", err)
	}
```

You're opening the same file with both local client and embedded replicas client. This is illegal. Embedded replicas have additional logic to handle replication. Local only client is not compatible with this logic. If you remove dbLocal, the dbRemoteEmbed should work.

**Comment by haaawk** [comment]
Just a comment about syncing embedded replicas:
If you do `NewEmbeddedReplicaConnectorWithAutoSync` instead of `NewEmbeddedReplicaConnector` then the sync will be done periodically automatically and you don't need all the:
```
	go func() {
		for true {
			_ = connector.Sync()
			time.Sleep(config.SyncInterval)
		}
	}()
```

**Comment by haaawk** [comment]
You're opening embedded replicas incorrectly. Instead of doing:
```
        connector, err := libsql.NewEmbeddedReplicaConnector(absPath, config.DatabaseUrl, *config.DatabaseAuthToken)
...
	db, err := sqlx.Open("libsql", "file://"+absPath)
```
the correct way is to do:
```
        connector, err := libsql.NewEmbeddedReplicaConnector(absPath, config.DatabaseUrl, *config.DatabaseAuthToken)
        ...
        db := sql.OpenDB(connector)
```
What you did was opening embedded replica file with a local only client and that makes it impossible for embedded replicas to work correctly.

**Comment by juliuslipp** [comment]
You are right. Last time I tried the auto-sync, it didn't work. That was a few versions ago though.

Ok let me try it.

**Comment by haaawk** [comment]
> You're opening embedded replicas incorrectly. Instead of doing:
> 
> ```
>         connector, err := libsql.NewEmbeddedReplicaConnector(absPath, config.DatabaseUrl, *config.DatabaseAuthToken)
> ...
> 	db, err := sqlx.Open("libsql", "file://"+absPath)
> ```
> 
> the correct way is to do:
> 
> ```
>         connector, err := libsql.NewEmbeddedReplicaConnector(absPath, config.DatabaseUrl, *config.DatabaseAuthToken)
>         ...
>         db := sql.OpenDB(connector)
> ```
> 
> What you did was opening embedded replica file with a local only client and that makes it impossible for embedded replicas to work correctly.

If you care about sqlx then you can do:
```
db := sqlx.NewDb(sql.OpenDB(connector), "libsql")
```

**Comment by juliuslipp** [comment]
Embedded replicas seem to work. Still having the stream_expired issue, any thoughts on that? Should I open a connection each time? Since this is happening under the hood in tursodb/libsql-go i'd expect it work the same way.

I'll deploy it to staging and let it run for a while to see if things work out.

**Comment by haaawk** [comment]
So the NewEmbeddedClient would look like:
```
func NewEmbeddedClient(config ClientConfig) (*Client, error) {
	absPath, _ := filepath.Abs("./sqlite.db")
	connector, err := libsql.NewEmbeddedReplicaConnectorWithAutoSync(absPath, config.DatabaseUrl, *config.DatabaseAuthToken, config.SyncInterval)
	if err != nil {
		return nil, err
	}

	db := sqlx.NewDb(sql.OpenDB(connector), "libsql")

	err = db.Ping()
	if err != nil {
		return nil, err
	}

	return db, nil
}
```

**Comment by haaawk** [comment]
> Embedded replicas seem to work. Still having the stream_expired issue, any thoughts on that? Should I open a connection each time? Since this is happening under the hood in tursodb/libsql-go i'd expect it work the same way.
> 
> I'll deploy it to staging and let it run for a while to see if things work out.

Returning the connection to the pool is one way to solve the issue.
Another would be to send ping over that connection every <10s
There should be a third way but I need to see if it's even accessible with sqlx.

**Comment by haaawk** [comment]
> > Embedded replicas seem to work. Still having the stream_expired issue, any thoughts on that? Should I open a connection each time? Since this is happening under the hood in tursodb/libsql-go i'd expect it work the same way.
> > I'll deploy it to staging and let it run for a while to see if things work out.
> 
> Returning the connection to the pool is one way to solve the issue. Another would be to send ping over that connection every <10s There should be a third way but I need to see if it's even accessible with sqlx.

Actually I just checked and sending pings is probably the only way for this to work. It seems that there is a bug in the code that returning the connection to the pool is not restarting the timeout. That's why you're seeing this. I will try to fix that.

**Comment by juliuslipp** [comment]
Even with sending pings it still fails (I ping the DB and its not erroring, but the query still fails)

![image](https://github.com/libsql/go-libsql/assets/43986145/2b3d23ae-aa59-4c46-8970-b8d673d6b915)

**Comment by haaawk** [comment]
There are two options:
1. Limit connection pool to 1 connection + Ping -> `DB.SetMaxIdleConns(1)`
2. Limit connection idle lifetime to 9s and then you don't need Ping at all -> `DB.SetConnMaxIdleTime(9s)`

**Comment by juliuslipp** [comment]
Great works! Thank you.

I think it would make sense to document this or add defaults. Was quite confused about why it's not working. 

Could you look into the empty-db issue? I think having some kind of functionality to prevent that would be great.

**Comment by haaawk** [comment]
I'm looking into fixing the expired stream for good so that it does not require any pool config.

**Comment by juliuslipp** [comment]
When you delete the sqlite.db file, but keep the client_wal_index, and recreate the embedded replica the DB will be empty.

**Comment by haaawk** [comment]
> When you delete the sqlite.db file, but keep the client_wal_index, and recreate the embedded replica the DB will be empty.

This is a very grey territory. I would strongly recommend to always start with a correct pair of data + wal files. Either both empty or both created by embedded replicas client and not touched by anything else. Including sqlite3 command line.

**Comment by juliuslipp** [comment]
This makes sense, but sometimes weird stuff happens and last time I didn't touch anything for weeks and it randomly broke after the server restarted. Guess because the files where corrupted, so a check beforehand would probably make sense for the first connection.

It seems to work smoothly locally now. I can build and run the docker image and query and insert data without any problems. 

When it comes to the deployment though, the app starts and works fine until I try to query data. It then dies without any error message:
```
2024-02-16T15:33:31.607 app sjc [info] INFO Main child exited with signal (with signal 'SIGSEGV', core dumped? false)
```

Any thoughts why this happens?

**Comment by haaawk** [comment]
> This makes sense, but sometimes weird stuff happens and last time I didn't touch anything for weeks and it randomly broke after the server restarted. Guess because the files where corrupted, so a check beforehand would probably make sense for the first connection.

We found and fixed a few bugs in the recent weeks.

> 
> It seems to work smoothly locally now. I can build and run the docker image and query and insert data without any problems.
> 
> When it comes to the deployment though, the app starts and works fine until I try to query data. It then dies without any error message:
> 
> ```
> 2024-02-16T15:33:31.607 app sjc [info] INFO Main child exited with signal (with signal 'SIGSEGV', core dumped? false)
> ```
> 
> Any thoughts why this happens?

Would you be able to share a reproducer? I'd love to have a look.

**Comment by juliuslipp** [comment]
You can deploy it to fly (I think it doesn't die, but the nil pointer is still there) with the repo I shared. 

```
fly launch
```

to launch a new app and just navigate to the url.

**Comment by haaawk** [comment]
> You can deploy it to fly (I think it doesn't die, but the nil pointer is still there) with the repo I shared.
> 
> ```
> fly launch
> ```
> 
> to launch a new app and just navigate to the url. Add the changes you suggested beforehand :)

Could you just commit the code you have? If I do changes myself there's a good chance we will end up with different code.

**Comment by juliuslipp** [comment]
done

**Comment by haaawk** [comment]
> done

Thanks!

**Comment by haaawk** [comment]
This should already be fixed

**Comment by bryanvaz** [comment]
@haaawk, this is still an issue and not fixed in the CGO version, but works and is not an issue for the non-CGO version. Is this intentional?

We just restarted development on a product that was supposed to use turso on the server side, and we just hit this issue on day 2 of development. I double checked against the examples to see if the original devs missed something, but their code aligns with the go example client code.

The issue is still present in this library (`github.com/tursodatabase/go-libsql`), but is not present in the `github.com/tursodatabase/libsql-client-go/libsql` library. This means that if we have a "embedded replica" connection for one of our libsql connections, we cannot use the same library to fallback to "remote-only", or reuse the connection code for a "remote-only" connection to another db.

We've tested it both with `turso dev` and `docker libsql` and we get the same `Hrana: api error: STREAM_EXPIRED` error.

Let me know if you need a github to reproduce this.
