### ISSUE TITLE
Turso Quickstart GO tutorial outdated

### ISSUE THREAD

**Issue by renatillas** [tursodatabase/go-libsql#17]
The installation of the Quickstart for Go still references the old url:
```sh
go get github.com/libsql/go-libsql
```
Running the command throws the following output:
```sh
go: downloading github.com/libsql/go-libsql v0.0.0-20240306141008-c20f26b667e5
go: github.com/libsql/go-libsql@upgrade (v0.0.0-20240306141008-c20f26b667e5) requires github.com/libsql/go-libsql@v0.0.0-20240306141008-c20f26b667e5: parsing go.mod:
        module declares its path as: github.com/tursodatabase/go-libsql
                but was required as: github.com/libsql/go-libsql
```

Simply changing it to:
```sh
go get github.com/tursodatabase/go-libsql
```
would solve the error

**Comment by haaawk** [comment]
@notrab @xinnks FYI

**Comment by notrab** [comment]
This is now fixed @renatillas 

Btw, all pages of our docs are in this repo. You can always submit a PR with any improvements, we'd be happy to review them 🙏🏻

**Comment by notrab** [comment]
@haaawk I don't have permission to close this issue.
