### ISSUE TITLE
Problems scanning to time.Time

### ISSUE THREAD

**Issue by lahickey** [tursodatabase/go-libsql#19]
If you have a structure something like this: 

```Go
type Result struct {
    Timestamp time.Time
    Other     int
}
```

... and scan results like this - so that there is another element expected *AFTER* the timestamp: 
```Go
var result Result
row.Scan(
    &result.Timestamp,
    &result.Other,
)
```
then it fails to scan Other because it actually only scans one value.

This is because the code that attempts the time.Time parsing:
https://github.com/tursodatabase/go-libsql/blob/d8f1df912132acd0af5ce83c9572d08d5f70ce51/libsql.go#L742-L745

incorrectly `return`s as soon as it has successfully parsed the time, aborting the `Next()` function before it processes the subsequent results.

It can be fixed in a few ways but probably the best is with a labelled continue. For instance, add a label before the outer loop on line 687: 

```Go
OuterLoop:
    for i := 0; i < count; i++ {
        var columnType C.int
```
and update the parsing code to:
```Go
if t, err := time.ParseInLocation(format, str, time.UTC); err == nil {
    dest[i] = t
    continue OuterLoop
}
```

Incidentally, this approach to dealing with time.Time is horribly inefficient because every time I scan a string (not a time.Time), it'll attempt, and fail, to convert it to 9 separate time formats. Lots of wasted work!

Is it possible to expose libsql column decltypes so that we can know this column is specified as a TIMESTAMP in the schema and therefore only attempt the conversion when required?

**Comment by haaawk** [comment]
Good catch. Thank you for your contribution @lahickey 

I will try to think about how to make the handling of text field more efficient.

**Comment by lahickey** [comment]
Thanks. If you look here (https://gitlab.com/cznic/sqlite/-/blob/master/sqlite.go?ref_type=heads#L260-271), a common approach is to use sqlite's column decltype to decide if a conversion should happen - however, the C wrapper (and therefore the go wrapper) do not expose those values so libsql wrappers would need updating.

Additionally I'd quite like the ability to switch that conversion of entirely because I almost never use native time.Time structures in my use-case and, when I do, I can handle the conversion application-side.
