### ISSUE TITLE
cannot find -lsql_experimental

### ISSUE THREAD

**Issue by just-Bri** [tursodatabase/go-libsql#33]
Might be the same problem as https://github.com/tursodatabase/go-libsql/issues/30

I'm writting a program using `raylib-go` and `go-libsql`, currently working on linux.
Current build command I'm trying on Linux:
```bash
CGO_ENABLED=1 CC=x86_64-w64-mingw32-gcc GOOS=windows GOARCH=amd64 go build -o SLASI.exe -ldflags "-s -w"
```

When trying to build for windows I get the following error:
```bash
/usr/local/go/pkg/tool/linux_amd64/link: running x86_64-w64-mingw32-gcc failed: exit status 1
/usr/bin/x86_64-w64-mingw32-ld: cannot find -lsql_experimental: No such file or directory
collect2: error: ld returned 1 exit status
```

I've tried the steps in the readme and some other different ways to force it to build but no luck so far

**Comment by haaawk** [comment]
Unfortunately, Windows is not currently supported. We don't have machines to build binaries for Windows.
